version: "3.9"

services:
  mongo_db:
    container_name: "db_container"
    image: "mongo"
    restart: "always"
    volumes:
      - "mongo_db:/data/db"

  api:
    build: .
    ports:
      - "27017:27017"
    environment:
      PORT: "27017"
      MONGODB_URI: "mongodb://mongo_db:27017"
      DB_NAME: "test"
      NAME: "todo"
    depends_on:
      - "mongo_db"

volumes:
  mongo_db: {}

# version: '3.7'
# services:
#   mongodb_container:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db

# volumes:
#   mongodb_data_container: 